#!/bin/bash

_script()
{
  COMPREPLY=();
  local currentCompletionWord="${COMP_WORDS[COMP_CWORD]}";
	case "$currentCompletionWord" in
		--project=*)
			COMPREPLY=($(compgen -W "--project={kafka,kafka-test}" -- "$currentCompletionWord"))
			;;
		--*)
			COMPREPLY=($(compgen -W "--help --project"'='"{a,b} --master-ip= " -- "$currentCompletionWord"))
			;;
		-*)
			COMPREPLY=($(compgen -W "-h --help --project"'='"{a,b} --master-ip=" -- "$currentCompletionWord"))
			;;
		*)
			COMPREPLY=($(compgen -W "-h --help --project"'='"{a,b} --master-ip=" -- "$currentCompletionWord"))
			;;
	esac

	return 0
}

complete -F _script -o filenames ./script.sh
