#!/bin/bash

_script()
{
	COMPREPLY=();
	projects="kafka kafka-test"
	local currentCompletionWord="${COMP_WORDS[COMP_CWORD]}";
	local previousCompletionWord="${COMP_WORDS[COMP_CWORD-1]}"
	if [[ $previousCompletionWord = "=" ]]
	then
		previousCompletionWord=${COMP_WORDS[COMP_CWORD-2]}	
	fi
	case "$currentCompletionWord" in
		*)
			COMPREPLY=($(compgen -S\= -W "--project --master-ip" -- $currentCompletionWord))
			COMPREPLY+=($(compgen -W "-h --help" -- "$currentCompletionWord"))

			case $previousCompletionWord in
			--project)
				COMPREPLY=($(compgen -W "$projects" -- "${currentCompletionWord#=}"))
				;;
			--master-ip)
				COMPREPLY=($(compgen -W "zose-master01 zose-master02 zose-master03" -- "${currentCompletionWord#=}"))
				;;
			esac

			;;
	esac

	return 0
}

complete -o nospace -F _script ./script.sh
