#!/bin/bash

declare -A libraries

source ../Logger/logger

libraries[logger]="../Logger/logger"

link()
{
	library=$1
	local_copy="./$library"
	original_copy=${libraries[$library]}
	if [ -z $local_copy ]; 
	then
		cp $original_copy $local_copy
	fi
	source $local_copy 
}

update_local_copy()
{
	original_copy=$1
	local_copy=$2
	original_version=`head -3 $original_copy | grep "#version"`
	local_version=`head -3 $local_version | grep "#version"`

}

